apiVersion: v1
kind: Service
metadata:
  name: ta-server-nginx-service
  #namespace: server
  labels:
    app: ta-server
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8080
  selector:
    app: ta-server
---
apiVersion: net.gke.io/v1
kind: ServiceExport
metadata:
  labels:
    app: ta-server
  namespace: sharedvpc
  name: ta-server-nginx-service
