apiVersion: networking.gke.io/v1
kind: MultiClusterIngress
metadata:
  labels:
    app: ta-server
  name: ta-server-ingress
spec:
  template:
    spec:
      backend:
        serviceName: ta-server-service
        servicePort: 8080

