apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata:
  labels:
    app: ta-server
  name: ta-server-service
spec:
  template:
    spec:
      selector:
        app: ta-server
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080

