apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: ta-server-destionationrule
spec:
  host: ta-server-service.sharedvpc.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      localityLbSetting:
        enabled: true
        failover:
        - from: asia-southeast1
          to: australia-southeast1
        - from: australia-southeast1
          to: asia-southeast1

    outlierDetection:
      splitExternalLocalOriginErrors: true
      consecutiveLocalOriginFailures: 10

      consecutive5xxErrors: 1
      interval: 1s
      baseEjectionTime: 2s
